In [1]:
# !pip install psycopg2-binary sqlalchemy pandas

In [2]:
# Import the required libraries
# pandas is used for data analysis and handling DataFrames
# create_engine from SQLAlchemy is used to connect Python to PostgreSQL
import pandas as pd
from sqlalchemy import create_engine

# Connect Python to PostgreSQL database
# Create a connection to the PostgreSQL database
# Format: postgresql://username:password@host:port/database
engine = create_engine(
    "postgresql://postgres:Chimodoi1810@localhost:5433/data_science_db"
)

# Execute an SQL query to retrieve all rows from the climate_data table
# The result is automatically converted into a Pandas DataFrame
df = pd.read_sql("SELECT * FROM climate_data", engine)

# Display the DataFrame in the notebook output
df

   id        date  temperature  humidity  covid_cases
0   1  2020-01-01         25.3      60.0           12
1   2  2020-01-02         26.1      58.0           18
2   3  2020-01-03         24.7      65.0            9
3   7  2020-01-04         27.0      63.0           20

In [3]:
# Check the number of rows in the table
row_count = pd.read_sql("""
    -- Count total observations in the dataset
    SELECT COUNT(*) AS total_rows
    FROM climate_data
""", engine)

row_count

   total_rows
0           4

In [4]:
# import pandas as pd
# from sqlalchemy import create_engine

# engine = create_engine(
#     "postgresql://postgres:Chimodoi1810@localhost:5433/data_science_db"
# )

# df = pd.read_sql("SELECT * FROM climate_data", engine)

# print(df)

In [5]:
# Compute summary statistics directly in PostgreSQL
summary = pd.read_sql("""
    -- Calculate average temperature, humidity, and total cases
    SELECT
        AVG(temperature) AS avg_temperature,
        AVG(humidity) AS avg_humidity,
        SUM(covid_cases) AS total_cases
    FROM climate_data
""", engine)

summary

   avg_temperature  avg_humidity  total_cases
0           25.775          61.5           59

In [6]:
# Identify duplicated records in the dataset
duplicates = pd.read_sql("""
    -- Find duplicate observations based on all variables except id
    SELECT date, temperature, humidity, covid_cases, COUNT(*) AS occurrences
    FROM climate_data
    GROUP BY date, temperature, humidity, covid_cases
    HAVING COUNT(*) > 1
""", engine)

duplicates

Empty DataFrame
Columns: [date, temperature, humidity, covid_cases, occurrences]
Index: []

In [7]:
# Import the text function for executing raw SQL statements
from sqlalchemy import text

# Open a connection to PostgreSQL and execute the deletion query
with engine.connect() as conn:
    conn.execute(text("""
        -- Delete duplicate rows while keeping the first occurrence
        DELETE FROM climate_data
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM climate_data
            GROUP BY date, temperature, humidity, covid_cases
        )
    """))
    
    # Commit the transaction to apply the changes
    conn.commit()

In [8]:
# Check if duplicate records still exist
duplicates = pd.read_sql("""
    -- Identify duplicate rows
    SELECT date, temperature, humidity, covid_cases, COUNT(*) AS occurrences
    FROM climate_data
    GROUP BY date, temperature, humidity, covid_cases
    HAVING COUNT(*) > 1
""", engine)

duplicates

Empty DataFrame
Columns: [date, temperature, humidity, covid_cases, occurrences]
Index: []

In [9]:
# Load the cleaned dataset from PostgreSQL
df = pd.read_sql("""
    -- Retrieve the climate dataset ordered by date
    SELECT *
    FROM climate_data
    ORDER BY date
""", engine)

df

   id        date  temperature  humidity  covid_cases
0   1  2020-01-01         25.3      60.0           12
1   2  2020-01-02         26.1      58.0           18
2   3  2020-01-03         24.7      65.0            9
3   7  2020-01-04         27.0      63.0           20

In [10]:
# -----------------------------------------------------------
# Load the cleaned dataset from PostgreSQL
# -----------------------------------------------------------

import pandas as pd
from sqlalchemy import create_engine

# Create database connection
engine = create_engine(
    "postgresql://postgres:Chimodoi1810@localhost:5433/data_science_db"
)

# Retrieve dataset from PostgreSQL
df = pd.read_sql("""
    -- Retrieve the climate dataset ordered by date
    SELECT *
    FROM climate_data
    ORDER BY date
""", engine)

# Display dataset
print(df)

# -----------------------------------------------------------
# Save dataset to CSV for dashboard deployment
# -----------------------------------------------------------

df.to_csv(
    "climate_data.csv",
    index=False
)

print("Dataset successfully saved as climate_data.csv")

   id        date  temperature  humidity  covid_cases
0   1  2020-01-01         25.3      60.0           12
1   2  2020-01-02         26.1      58.0           18
2   3  2020-01-03         24.7      65.0            9
3   7  2020-01-04         27.0      63.0           20
Dataset successfully saved as climate_data.csv

In [12]:
# -----------------------------------------------------------
# Load the cleaned dataset from PostgreSQL
# -----------------------------------------------------------

import pandas as pd
from sqlalchemy import create_engine

# Create PostgreSQL connection
engine = create_engine(
    "postgresql://postgres:Chimodoi1810@localhost:5433/data_science_db"
)

# Retrieve the dataset
df = pd.read_sql("""
    -- Retrieve the climate dataset ordered by date
    SELECT *
    FROM climate_data
    ORDER BY date
""", engine)

# Display the dataset
print(df)

# -----------------------------------------------------------
# Save dataset to the specified Windows directory
# -----------------------------------------------------------

file_path = r"D:\DESKTOP\SQL\climate-dashboard\climate_data.csv"

df.to_csv(file_path, index=False)

print("Dataset successfully saved to:", file_path)

   id        date  temperature  humidity  covid_cases
0   1  2020-01-01         25.3      60.0           12
1   2  2020-01-02         26.1      58.0           18
2   3  2020-01-03         24.7      65.0            9
3   7  2020-01-04         27.0      63.0           20
Dataset successfully saved to: D:\DESKTOP\SQL\climate-dashboard\climate_data.csv

In [ ]:
with engine.begin() as conn:
    conn.execute(text("""
        -- Prevent identical records from being inserted again
        ALTER TABLE climate_data
        ADD CONSTRAINT unique_climate_record
        UNIQUE (date, temperature, humidity, covid_cases)
    """))

# Exploratory Data Analysis

In [ ]:
# Inspect the structure of the dataset
df.info()

In [ ]:
# Convert date column from string to datetime format
df['date'] = pd.to_datetime(df['date'])

# Verify the updated data types
df.info()

In [ ]:
# Generate summary statistics
df.describe()

In [ ]:
# Compute correlation matrix between climate variables and COVID cases
df[['temperature','humidity','covid_cases']].corr()

In [ ]:
# import matplotlib.pyplot as plt

# # Plot COVID cases over time
# plt.plot(df['date'], df['covid_cases'])
# plt.xlabel("Date")
# plt.ylabel("COVID Cases")
# plt.title("COVID Cases Over Time")
# plt.show()

# Dashboard

In [ ]:
# Install dashboard libraries
# !pip install dash plotly psycopg2-binary sqlalchemy pandas

In [ ]:
# Import required libraries
import pandas as pd
from sqlalchemy import create_engine
import dash
from dash import dcc, html
import plotly.express as px

# Connect to PostgreSQL database
engine = create_engine(
    "postgresql://postgres:Chimodoi1810@localhost:5433/data_science_db"
)

# Load dataset
df = pd.read_sql("SELECT * FROM climate_data", engine)

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

In [ ]:
# Calculate KPI metrics
total_cases = df['covid_cases'].sum()
avg_temp = round(df['temperature'].mean(),2)
avg_humidity = round(df['humidity'].mean(),2)
num_records = len(df)

In [ ]:
# COVID cases over time
cases_trend = px.line(
    df,
    x='date',
    y='covid_cases',
    title="COVID Cases Over Time"
)

# Temperature and humidity trend
climate_trend = px.line(
    df,
    x='date',
    y=['temperature','humidity'],
    title="Temperature and Humidity Trends"
)

# Temperature vs cases
scatter_temp = px.scatter(
    df,
    x='temperature',
    y='covid_cases',
    title="Temperature vs COVID Cases"
)

# Humidity vs cases
scatter_humidity = px.scatter(
    df,
    x='humidity',
    y='covid_cases',
    title="Humidity vs COVID Cases"
)

# Correlation matrix
corr = df[['temperature','humidity','covid_cases']].corr()

heatmap = px.imshow(
    corr,
    text_auto=True,
    title="Correlation Matrix"
)

In [ ]:
# Temperature distribution
temp_hist = px.histogram(df, x="temperature", title="Temperature Distribution")

# Humidity distribution
humidity_hist = px.histogram(df, x="humidity", title="Humidity Distribution")

# COVID cases distribution
cases_hist = px.histogram(df, x="covid_cases", title="COVID Case Distribution")

In [ ]:
# Create Dash app
app = dash.Dash(__name__)

app.layout = html.Div([

    html.H1("Climate and COVID Dashboard"),

    # KPI Cards
    html.Div([
        html.Div(f"Total Cases: {total_cases}", style={'padding':20}),
        html.Div(f"Average Temperature: {avg_temp}", style={'padding':20}),
        html.Div(f"Average Humidity: {avg_humidity}", style={'padding':20}),
        html.Div(f"Records: {num_records}", style={'padding':20}),
    ], style={'display':'flex','justify-content':'space-around'}),

    dcc.Graph(figure=cases_trend),

    dcc.Graph(figure=climate_trend),

    html.Div([
        dcc.Graph(figure=scatter_temp),
        dcc.Graph(figure=scatter_humidity)
    ], style={'display':'flex'}),

    dcc.Graph(figure=heatmap),

    html.Div([
        dcc.Graph(figure=temp_hist),
        dcc.Graph(figure=humidity_hist),
        dcc.Graph(figure=cases_hist)
    ], style={'display':'flex'})
])

In [ ]:
# Run the dashboard server
if __name__ == "__main__":
    app.run(debug=True)

# Real-Time Dashboard

In [ ]:
# -----------------------------------------------------------
# Climate and COVID Analytical Dashboard
# -----------------------------------------------------------
# This script creates a real-time dashboard using Plotly Dash.
# The dashboard retrieves data from PostgreSQL and refreshes
# automatically every 10 seconds when the database changes.
# -----------------------------------------------------------

# Import required libraries
import pandas as pd
from sqlalchemy import create_engine
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px

# -----------------------------------------------------------
# DATABASE CONNECTION
# -----------------------------------------------------------

# Create connection to PostgreSQL database
# Format:
# postgresql://username:password@host:port/database
engine = create_engine(
    "postgresql://postgres:Chimodoi1810@localhost:5433/data_science_db"
)

# -----------------------------------------------------------
# FUNCTION TO LOAD DATA FROM DATABASE
# -----------------------------------------------------------

def load_data():
    """
    Retrieve updated dataset from PostgreSQL.
    This function is called every time the dashboard refreshes.
    """

    query = """
        SELECT *
        FROM climate_data
        ORDER BY date
    """

    # Load SQL query results into a Pandas DataFrame
    df = pd.read_sql(query, engine)

    # Convert date column into datetime format
    df['date'] = pd.to_datetime(df['date'])

    return df


# -----------------------------------------------------------
# INITIALISE DASH APPLICATION
# -----------------------------------------------------------

app = dash.Dash(__name__)

# -----------------------------------------------------------
# DASHBOARD LAYOUT
# -----------------------------------------------------------

app.layout = html.Div([

    # Dashboard title
    html.H1("Climate and COVID Monitoring Dashboard"),

    # -------------------------------------------------------
    # INTERVAL COMPONENT
    # -------------------------------------------------------
    # This component triggers the dashboard update every
    # 10 seconds (10000 milliseconds).
    # -------------------------------------------------------
    dcc.Interval(
        id='interval-refresh',
        interval=10*1000,   # refresh every 10 seconds
        n_intervals=0
    ),

    # -------------------------------------------------------
    # KPI CARDS SECTION
    # -------------------------------------------------------
    html.Div(id="kpi-cards"),

    # -------------------------------------------------------
    # TIME SERIES CHART
    # -------------------------------------------------------
    dcc.Graph(id="cases-trend"),

    # -------------------------------------------------------
    # CLIMATE TREND CHART
    # -------------------------------------------------------
    dcc.Graph(id="climate-trend"),

    # -------------------------------------------------------
    # SCATTER RELATIONSHIPS
    # -------------------------------------------------------
    html.Div([
        dcc.Graph(id="scatter-temp"),
        dcc.Graph(id="scatter-humidity")
    ], style={'display':'flex'}),

    # -------------------------------------------------------
    # CORRELATION HEATMAP
    # -------------------------------------------------------
    dcc.Graph(id="correlation-heatmap"),

    # -------------------------------------------------------
    # DISTRIBUTION HISTOGRAMS
    # -------------------------------------------------------
    html.Div([
        dcc.Graph(id="temp-distribution"),
        dcc.Graph(id="humidity-distribution"),
        dcc.Graph(id="cases-distribution")
    ], style={'display':'flex'})

])


# -----------------------------------------------------------
# DASH CALLBACK FOR AUTOMATIC DASHBOARD REFRESH
# -----------------------------------------------------------
# This function is triggered by the interval component.
# Each trigger re-queries PostgreSQL and updates all charts.
# -----------------------------------------------------------

@app.callback(

    [
        Output("kpi-cards","children"),
        Output("cases-trend","figure"),
        Output("climate-trend","figure"),
        Output("scatter-temp","figure"),
        Output("scatter-humidity","figure"),
        Output("correlation-heatmap","figure"),
        Output("temp-distribution","figure"),
        Output("humidity-distribution","figure"),
        Output("cases-distribution","figure")
    ],

    [Input("interval-refresh","n_intervals")]

)
def update_dashboard(n):

    # Load latest dataset from PostgreSQL
    df = load_data()

    # -------------------------------------------------------
    # COMPUTE KPI METRICS
    # -------------------------------------------------------
    total_cases = df['covid_cases'].sum()
    avg_temp = round(df['temperature'].mean(),2)
    avg_humidity = round(df['humidity'].mean(),2)
    records = len(df)

    # KPI display cards
    kpi_cards = html.Div([
        html.Div(f"Total Cases: {total_cases}"),
        html.Div(f"Average Temperature: {avg_temp}"),
        html.Div(f"Average Humidity: {avg_humidity}"),
        html.Div(f"Records: {records}")
    ], style={'display':'flex','justify-content':'space-around'})

    # -------------------------------------------------------
    # CREATE VISUALISATIONS
    # -------------------------------------------------------

    # COVID cases time trend
    cases_trend = px.line(
        df,
        x='date',
        y='covid_cases',
        title="COVID Cases Over Time"
    )

    # Temperature and humidity trend
    climate_trend = px.line(
        df,
        x='date',
        y=['temperature','humidity'],
        title="Temperature and Humidity Trends"
    )

    # Scatter: temperature vs cases
    scatter_temp = px.scatter(
        df,
        x='temperature',
        y='covid_cases',
        title="Temperature vs COVID Cases"
    )

    # Scatter: humidity vs cases
    scatter_humidity = px.scatter(
        df,
        x='humidity',
        y='covid_cases',
        title="Humidity vs COVID Cases"
    )

    # Correlation heatmap
    corr = df[['temperature','humidity','covid_cases']].corr()

    heatmap = px.imshow(
        corr,
        text_auto=True,
        title="Correlation Matrix"
    )

    # Distribution histograms
    temp_hist = px.histogram(df,x="temperature",
                             title="Temperature Distribution")

    humidity_hist = px.histogram(df,x="humidity",
                                 title="Humidity Distribution")

    cases_hist = px.histogram(df,x="covid_cases",
                              title="COVID Case Distribution")

    # Return all dashboard elements
    return (kpi_cards,
            cases_trend,
            climate_trend,
            scatter_temp,
            scatter_humidity,
            heatmap,
            temp_hist,
            humidity_hist,
            cases_hist)


# -----------------------------------------------------------
# RUN DASHBOARD SERVER
# -----------------------------------------------------------

if __name__ == "__main__":
    app.run(debug=True)